# Generated by Django 4.2.6 on 2023-10-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='race',
        ),
        migrations.AddField(
            model_name='fighter',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighters.race'),
        ),
    ]
