# Generated by Django 4.2.6 on 2023-10-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_alter_fighter_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='weapon',
        ),
        migrations.AddField(
            model_name='fighter',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighters.weapon'),
        ),
    ]
