# Generated by Django 4.2.6 on 2023-10-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_remove_fighter_weapon_fighter_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/fighters/'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fighters.weapon'),
        ),
    ]
